rev 10.07.2025


La deserción y permanencia estudiantil son aspectos críticos que Unitrópico aborda a través de un **marco estratégico integral**, arraigado en su Proyecto Educativo Institucional (PEI) y políticas específicas [PEI2021.md 280, 284, 285, textopei_ES.pdf 721, 728, 730]. Este enfoque se desarrolla en respuesta a los desafíos nacionales en educación superior y el compromiso de la universidad con la **calidad y la formación integral** de sus estudiantes [PEI2021.md 278, textopei_ES.pdf 722].

A continuación, se sintetizan los puntos clave sobre la deserción y permanencia estudiantil en Unitrópico:

*   **Contexto y Reconocimiento del Problema**:
    *   La educación superior en Colombia enfrenta retos en calidad, financiación y eficiencia, así como la necesidad de **eliminar barreras de acceso e integración** para todos los actores de la sociedad [PEI2021.md 284, textopei_ES.pdf 728].
    *   En 2016, la tasa de deserción en el departamento de Casanare fue del **19,5%**, con una alta concentración de estudiantes en Yopal [PEI2021.md 285, textopei_ES.pdf 730].
    *   El programa de Economía de Unitrópico busca **disminuir esta brecha** entre inscritos y matriculados a través de estrategias de retención de aspirantes y una malla curricular flexible [PEP ECONOMÍA.pdf 370, 372]. El nivel de deserción en el área de Economía a nivel nacional fue del 14.81% en 2015, reduciéndose al 13.65% en 2018 [PEP ECONOMÍA.pdf 371].

*   **Políticas y Estrategias Fundamentales**:
    *   El **Bienestar Universitario** es concebido como una **tarea misional y un eje transversal** a todas las áreas del PEI, buscando el desarrollo humano integral de la comunidad universitaria [2. ACUERDO CS No. 044 DE 2023 - Politica de Bienestar.pdf 49, PEP ADMINISTRACIÓN DE EMPRESAS (1).pdf 346, UNITROPICO-BIENESTAR.m4a 683, 685].
    *   La **Política Integral de Bienestar Universitario (PIBU)** plasma lineamientos conceptuales y estratégicos para el desarrollo humano integral de la comunidad, ratificando el compromiso con las normas nacionales para la calidad educativa [2. ACUERDO CS No. 044 DE 2023 - Politica de Bienestar.pdf 41].
    *   Las instituciones de educación superior deben adelantar **programas de bienestar** que se orienten al desarrollo físico, psico-afectivo, espiritual y social de estudiantes, docentes y personal administrativo, según la Ley 30 de 1992 [2. ACUERDO CS No. 044 DE 2023 - Politica de Bienestar.pdf 38, 43, RESOLUCIÓN No 020 DE 2021 - Estatuto de Bienestar Universitario.pdf 667].
    *   La **permanencia y graduación** es una línea de acción clave de la PIBU, apoyada por estrategias de prevención y mitigación de la deserción, incluyendo **sistemas de alertas tempranas** [2. ACUERDO CS No. 044 DE 2023 - Politica de Bienestar.pdf 52, 59, PEP ADMINISTRACIÓN DE EMPRESAS (1).pdf 347, PEP ESPECIALIZACIÓN EN EVALUACIÓN Y GESTIÓN AMBIENTAL.pdf 441, 442, UNITROPICO-BIENESTAR.m4a 683, 687, 692].

*   **Acciones y Componentes del Plan de Permanencia y Acompañamiento**:
    *   **Apoyo Académico**: Incluye **cursos de nivelación** para estudiantes de primer ingreso en competencias básicas, caracterización de estudiantes en riesgo, acompañamiento grupal a través de monitorías, y tutorías individuales [PEP ADMINISTRACIÓN DE EMPRESAS (1).pdf 348, PEP ESPECIALIZACIÓN EN EVALUACIÓN Y GESTIÓN AMBIENTAL.pdf 443, RESOLUCIÓN No 020 DE 2021 - Estatuto de Bienestar Universitario.pdf 672, Proyecto Educativo de Medicina Veterinaria y Zootecnia.pdf 591, 592, PEP Ingeniería Civil - DOCUMENTO JUN 2024 (1).pdf 469].
    *   **Apoyo Psicosocial**: Comprende planes de identificación y seguimiento de estudiantes en conductas de riesgo, estrategias de prevención y promoción de salud mental, y acciones para fortalecer capacidades humanas [PEP ADMINISTRACIÓN DE EMPRESAS (1).pdf 349, 350, PEP ESPECIALIZACIÓN EN EVALUACIÓN Y GESTIÓN AMBIENTAL.pdf 444, UNITROPICO-BIENESTAR.m4a 685, 688, 692].
    *   **Gestión Universitaria**: Implica atención en salud de primer nivel, diversificación de la oferta curricular y ampliación de oportunidades de acceso a la educación [PEP ADMINISTRACIÓN DE EMPRESAS (1).pdf 350, PEP ESPECIALIZACIÓN EN EVALUACIÓN Y GESTIÓN AMBIENTAL.pdf 444].
    *   **Apoyo Financiero/Socioeconómico**: Ofrece programas para favorecer la alimentación, movilidad y alojamiento de estudiantes en condiciones socioeconómicas bajas, así como acompañamiento en el proceso de emprendimiento [PEP ADMINISTRACIÓN DE EMPRESAS (1).pdf 351, PEP ESPECIALIZACIÓN EN EVALUACIÓN Y GESTIÓN AMBIENTAL.pdf 445]. También se otorgan **bonos económicos de alimentación** a estudiantes en situación de vulnerabilidad [Anexo 17. Proyecto Educativo del Programa de Arquitectura.pdf 164, UNITROPICO-BIENESTAR.m4a 684].
    *   **Ruta Integral de Acompañamiento y Seguimiento Estudiantil**: Consiste en 8 pasos que van desde la identificación de vulnerabilidad por parte del profesor hasta la evaluación y ajustes de la intervención, involucrando a diversas áreas como Bienestar Universitario, Vicerrectoría Académica y profesionales de psicología y enfermería [PEP ADMINISTRACIÓN DE EMPRESAS (1).pdf 351, 352, PEP ESPECIALIZACIÓN EN EVALUACIÓN Y GESTIÓN AMBIENTAL.pdf 445, 446].

*   **Inclusión y Diversidad**:
    *   La universidad promueve la **educación superior inclusiva e intercultural**, reconociendo la diversidad sociocultural y las necesidades de poblaciones con discapacidad o talentos excepcionales [1. ACUERDO CS No. 043 DE 2023 - PESII.pdf 29, 31, 32, PEP ADMINISTRACIÓN DE EMPRESAS (1).pdf 354].
    *   Se implementa una **ruta de acompañamiento integral para la diversidad** y se fomenta el respeto por la diversidad y la interculturalidad [1. ACUERDO CS No. 043 DE 2023 - PESII.pdf 32, PEP ESPECIALIZACIÓN EN EVALUACIÓN Y GESTIÓN AMBIENTAL.pdf 443].

*   **Otros Factores de Permanencia**:
    *   La **flexibilidad curricular** permite a los estudiantes diseñar sus propias trayectorias académicas, elegir asignaturas optativas y adelantar o nivelar cursos, contribuyendo a la disminución de la deserción [PEP ECONOMÍA.pdf 372, 373, PEP ESPECIALIZACIÓN EN EVALUACIÓN Y GESTIÓN AMBIENTAL.pdf 432, PEP ADMINISTRACIÓN DE EMPRESAS (1).pdf 326].
    *   El **seguimiento de los egresados** y su impacto en el entorno social y académico es fundamental para fortalecer los lazos de pertenencia y colaboración, lo que también incide en la pertinencia de los programas académicos [PEP ADMINISTRACIÓN DE EMPRESAS (1).pdf 352, UNITROPICO-VICEEXT.m4a 696].
    *   Las **prácticas académicas y pasantías** son un medio inicial para que los estudiantes se relacionen con el entorno, adquieran experiencia y fortalezcan su sentido de pertenencia [UNITROPICO-VICEEXT.m4a 696].

En síntesis, Unitrópico ha desarrollado un **enfoque multifacético y colaborativo** para abordar la deserción y fomentar la permanencia, integrando el bienestar estudiantil, el apoyo académico, psicosocial y financiero, así como una política de inclusión y flexibilidad curricular, todo enmarcado en el propósito de formar profesionales integrales y comprometidos con su región y el mundo [PEI2021.md 280, 282, textopei_ES.pdf 724, 727].
